export enum TERRA_QUERY_KEY {
	TERRA_NATIVE_BALANCES = 'TERRA_NATIVE_BALANCES',
}

export enum ORNE_QUERY_KEY {
	ORNE_BALANCE = 'ORNE_BALANCE',
	ORNE_POOL = 'ORNE_POOL',
	ORNE_LP = 'ORNE_LP',
	ORNE_SHARE = 'ORNE_SHARE',
}
